name: Docker Image CI

on:
  push:
    branches: [ firdavs ]
  pull_request:
    branches: [ firdavs ]

jobs:

  build:

    runs-on: alpine3.13

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xfirdavsforUdevs:latest
    - name: Push the Docker
      run: docker login -u xfirdavs -p ${{ secrets.DOCKER_TOKEN }} && docker push xfirdavs/xfirdavsforUdevs:latest
